name: Build Trilink Custom Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Trilink Patch
        run: python patch_client.py

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Subindo para a 3.24 com o patch de sintaxe novo
          channel: 'stable'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate Bridge
        run: |
          cargo install flutter_rust_bridge_codegen --version 1.80.1
          # Adiciona o binário ao PATH do Windows para ser reconhecido no próximo passo
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          # Comando de geração
          $HOME/.cargo/bin/flutter_rust_bridge_codegen --rust-input libs/hbb_common/src/bridge_generated.rs --dart-output flutter/lib/generated_bridge.dart
        continue-on-error: true

      - name: Build Flutter Windows
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trilink-Suporte-Windows
          path: flutter/build/windows/runner/Release/