name: Build Trilink Custom Client

on:
  workflow_dispatch: # Disparo manual pelo botão no GitHub

permissions:
  contents: write # Permite que o robô salve o arquivo final

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Trilink Patch
        run: python patch_client.py

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Install VCPKG Dependencies
        run: |
          vcpkg install sdk7-windows:x64-windows-static-md

      - name: Build Flutter Windows
        env:
          VCPKG_ROOT: C:\smoketest\vcpkg
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # O PONTO CRÍTICO: Atualizado para v4
        with:
          name: Trilink-Suporte-Windows
          path: flutter/build/windows/runner/Release/